### ISSUE TITLE
stuck view if multiple contact Fetch

### ISSUE THREAD

**Issue by shraddha-patel-1891** [SwiftyContacts/SwiftyContacts#11]
Hello,
i have 18,000 contacts and load all contacts using swifty contact.
but when an app allows contact access permission then the entire app stuck nothing working in app 9 10 min.
so anyone has a solution then please update here.
please help me as soon as possible.

Thank you.

**Comment by shraddha-patel-1891** [comment]
Hello,
anyone have a solution then please help me.
I required solution urgently and I used swifty contact for fetch contact.

thank you

**Comment by satishbabariya** [comment]
@shraddha-patel-1891 try using background thread, or you can use activity indicator to show loading contacts progress.
