### ISSUE TITLE
Can not use contactToCSV

### ISSUE THREAD

**Issue by saitawngpha** [SwiftyContacts/SwiftyContacts#12]
Dear sir,
I try to use contactToCSV function. But I got the error like below. 
How to fix it?
Best,
STP
<img width="802" alt="Screen Shot 2019-08-31 at 12 35 59 PM" src="https://user-images.githubusercontent.com/9567660/64059955-11a11300-cbec-11e9-9e22-98a3355fa092.png">

**Comment by satishbabariya** [comment]
@saitawngpha, try using `let data` instead of data

**Comment by saitawngpha** [comment]
@satishbabariya, thx q sir! I will try it.
