### ISSUE TITLE
Terminating app due to uncaught exception 'CNPropertyNotFetchedException', reason: 'A property was not requested when contact was fetched.'

### ISSUE THREAD

**Issue by auc0le** [SwiftyContacts/SwiftyContacts#16]
Hello,

I am receiving this error:
Terminating app due to uncaught exception 'CNPropertyNotFetchedException', reason: 'A property was not requested when contact was fetched.'

When trying to access imageDataAvailable and / or imageData.

**Comment by abeticlairon** [comment]
Have you found a solution? I am facing the same issue.

**Comment by abeticlairon** [comment]
A working solution is not using imageDataAvailable but instead:

```
        if let contactPicture = contactList[indexPath.row].imageData {
            cell.contactPicture.image = UIImage(data: contactPicture)
        }
```

The problem arises at `imageDataAvailable`.
