### ISSUE TITLE
Error in function name

### ISSUE THREAD

**Issue by DevulderJeanPaul** [SwiftyContacts/SwiftyContacts#18]
public func fetchContactsInGorup(Group group: CNGroup, completionHandler: @escaping (_ result: Result<[CNContact], Error>) 
public func fetchContactsInGorup2(Group group: CNGroup, completionHandler: @escaping (_ result:  Result<[CNContact], Error>)

Correct name need to be fetchContactsInGroup
Correct name need to be fetchContactsInGroup2 i think

**Comment by satishbabariya** [comment]
@SwiftAppx can you elaborate the issue. because both `fetchContactsInGroup` and `fetchContactsInGroup2` are for the same functionality with different implementation
