### ISSUE TITLE
Adding support for fetching imageData in CNContact

### ISSUE THREAD

**Issue by zkhalapyan** [SwiftyContacts/SwiftyContacts#21]
Seems like `CNContactImageDataAvailableKey` and `CNContactThumbnailImageDataKey` are not included in the `CNContactVCardSerialization.descriptorForRequiredKeys()`, which results in a crash when I attempt to fetch the image data. 

Have you seen/consider this issue in the past?

```Swift
// Generated error: "A property was not requested when contact was fetched." 
if (contact.imageDataAvailable) {
    Image(data: contact.imageData)
}
```

**Comment by wertpoiu** [comment]
> Have you seen/consider this issue in the past?

Same here, its crashing.

**Comment by satishbabariya** [comment]
@zkhalapyan and @wertpoiu, i've updated fetchContacts function with keysToFetch parameter, will this work for you guys?
```swift
fetchContacts(keysToFetch: [CNContactGivenNameKey, CNContactFamilyNameKey, CNContactThumbnailImageDataKey] as [CNKeyDescriptor]) { result in }

```

**Comment by zkhalapyan** [comment]
Nice! Haven't tried this, but pretty sure this would work. Closing it out for now.
