### ISSUE TITLE
Container contact source identifier

### ISSUE THREAD

**Issue by dngconsulting** [SwiftyContacts/SwiftyContacts#25]
Hello,

Thanks for this great lib. Do you know if it's possible to extract the container id identifier for a specific contact ? For now, it's only possible to get the universal id but I would want to reconciliate google accounts and ios contacts. Apple should store somewhere the initial google identifier.
Thanks

Sami

**Comment by kuls14** [comment]
@dngconsulting I want to add a similar feature like syncing iCloud contacts with Google contacts and vice versa but I don't have an idea how to implement that.
If you have any suggestions, can you please share it?
