### ISSUE TITLE
How can find duplicate contacts? there is no method. 

### ISSUE THREAD

**Issue by pethanihiten** [SwiftyContacts/SwiftyContacts#26]
![Screenshot 2021-02-25 at 12 07 59 PM](https://user-images.githubusercontent.com/20463766/109113338-1bb0bd00-7762-11eb-88ab-b22e5e4ca460.png)

**Comment by satishbabariya** [comment]
@pethanihiten, the newer version does not have this method but you can find this code in older versions,
Ref: https://github.com/satishbabariya/SwiftyContacts/blob/2.0.0/SwiftyContacts/Classes/SwiftyContacts.swift#L463

**Comment by pethanihiten** [comment]
ok thanks.

**Comment by pethanihiten** [comment]
we check this method and apply but return all contact not only duplicate?
