### ISSUE TITLE
Contact Update Notification

### ISSUE THREAD

**Issue by yudiz-mahavirsinh** [SwiftyContacts/SwiftyContacts#6]
2 Queries :
- Can I get notification/callback when user update/add/delete a contact in Device Contacts?
- can I get object/reference/id of that single contact when anything from above happens?

**Comment by satishbabariya** [comment]
You  can always use **CNContactStoreDidChange (NSNotification.Name)** notifications when changes occur in another CNContactStore

**Comment by yudiz-mahavirsinh** [comment]
I have used this but I'm not getting info like which contact is deleted/updated or added

**Comment by HarinderjitSingh** [comment]
@yudiz-mahavir did you find any solution for getting info like which contact is deleted/updated or added
